import { useState } from 'react'; import { Check, ChevronRight, Wrench } from 'lucide-react'; import { IndustrialHeader } from './IndustrialHeader';
interface Props{onComplete:()=>void;elapsedTime:number;toProduct:string;operatorSettings:{operatorName:string;line:string;station:string};onBack:()=>void;onSettings?:()=>void}
export function ChangeoverStep4Screen({onComplete,elapsedTime,toProduct,operatorSettings,onBack,onSettings}:Props){
  const needsHandle = toProduct === 'Product 1';

  const toolItems = needsHandle
    ? [{id:1,label:'M3-inbussleutel beschikbaar'},{id:2,label:'M5-inbussleutel beschikbaar'},{id:3,label:'Metaalvijl beschikbaar'},{id:4,label:'Bruikbaar'}]
    : [{id:1,label:'M3-inbussleutel beschikbaar'},{id:2,label:'Metaalvijl beschikbaar'},{id:3,label:'Bruikbaar'}];

  const [tools,setTools]=useState(toolItems.map(t=>({...t,checked:false})));
  const toggle=(id:number)=>setTools(p=>p.map(i=>i.id===id?{...i,checked:!i.checked}:i));
  const all=tools.every(i=>i.checked);

  return <div className="h-full min-h-0 flex flex-col bg-gray-100 overflow-hidden"><IndustrialHeader title="Omstelling, stap 4 van 5" subtitle="Gereedschap controleren" showTimer elapsedTime={elapsedTime} operatorSettings={operatorSettings} onBack={onBack} onSettings={onSettings}/><div className="flex-1 min-h-0 overflow-y-auto flex flex-col md:flex-row p-8 gap-8 max-w-[1280px] mx-auto w-full"><div className="flex-1 bg-white rounded-lg shadow-sm border border-gray-200 p-6 flex items-center justify-center"><Wrench className="w-32 h-32 text-gray-300"/></div><div className="w-full md:w-96 flex flex-col gap-5"><div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6"><div className="flex items-center gap-3 mb-3"><Wrench className="w-8 h-8 text-gray-700"/><h3 className="text-2xl text-gray-800 font-bold uppercase">Gereedschap check</h3></div><p className="text-sm text-gray-700">{toProduct} heeft {needsHandle ? 'een M3- en een M5-inbussleutel' : 'een M3-inbussleutel'} en een metaalvijl (voor het schuren van de profielen) nodig.</p></div><div className="bg-blue-50 border-l-4 border-blue-600 rounded-lg p-5"><h4 className="text-sm text-blue-800 font-bold mb-2 uppercase">Benodigd gereedschap</h4><div className="space-y-2">{(needsHandle ? ['M3-inbussleutel','M5-inbussleutel','Metaalvijl'] : ['M3-inbussleutel','Metaalvijl']).map(t=><div key={t} className="flex items-center gap-2"><span className="text-2xl text-blue-900 font-bold">1×</span><span className="text-lg text-blue-800">{t}</span></div>)}</div></div><div className="bg-white rounded-lg shadow-sm border border-gray-200 p-5">{tools.map(tool=><label key={tool.id} className="flex items-center gap-3 p-3 bg-gray-50 rounded mb-2"><input type="checkbox" checked={tool.checked} onChange={()=>toggle(tool.id)} className="w-6 h-6"/><span className="text-sm text-gray-800 flex-1">{tool.label}</span>{tool.checked&&<Check className="w-5 h-5 text-green-600"/>}</label>)}</div><div className="flex-1"></div><button onClick={onComplete} disabled={!all} className={`w-full text-lg py-4 px-6 rounded-lg flex items-center justify-center gap-3 font-medium ${all?'bg-blue-500 text-white':'bg-gray-300 text-gray-500'}`}>Tool OK<ChevronRight className="w-6 h-6"/></button></div></div></div>;
}
